package fr.mmouky.prosit.utils;

public enum TypeContenu {

	PA, CER, MEME, GROUPE,
	INFORMATIONS, MOTS_CLES, CONTEXTE, CONTRAINTES, GENERALISATION, PROBLEMATIQUE, HYPOTHESES, PLAN_DACTION, EMPTY

}
